Correct uses of `respond_to` in AnnotationDecider (#131)
In our project we have more than just Active Record models within our
`models` folder. After switching to this gem we noticed a couple errors
being raised when attempting to decide if some of those should be
annotated or not.

For example, a class that inherits from `Dry::Struct` responds to
`abstract_class` but not to `abstract_class?`.

```ruby
> class Demo < Dry::Struct; end
> Demo.abstract_class
=> Dry::Struct
> Demo.abstract_class?
(irb):3:in `<main>': undefined method `abstract_class?' for class Demo (NoMethodError)
```