Return a model files array even if it’s empty
Currently, when there are no available models, `ModelFilesGetter`
returns `nil` but callers are expecting it to return an array.

This makes the app crash with:
```
/home/discourse/.bundle/gems/ruby/3.3.0/gems/annotaterb-4.17.0/lib/annotate_rb/model_annotator/project_annotator.rb:13:in `annotate': undefined method `map' for nil (NoMethodError)

        annotation_instructions = project_model_files.map do |path, filename|
                                                     ^^^^
        from /home/discourse/.bundle/gems/ruby/3.3.0/gems/annotaterb-4.17.0/lib/annotate_rb/model_annotator/annotator.rb:21:in `do_annotations'
        from /home/discourse/.bundle/gems/ruby/3.3.0/gems/annotaterb-4.17.0/lib/annotate_rb/model_annotator/annotator.rb:8:in `do_annotations'
        from /home/discourse/.bundle/gems/ruby/3.3.0/gems/annotaterb-4.17.0/lib/annotate_rb/commands/annotate_models.rb:17:in `call'
        from /home/discourse/.bundle/gems/ruby/3.3.0/gems/annotaterb-4.17.0/lib/annotate_rb/runner.rb:24:in `run'
        from /home/discourse/.bundle/gems/ruby/3.3.0/gems/annotaterb-4.17.0/lib/annotate_rb/runner.rb:7:in `run'
        from /home/discourse/.bundle/gems/ruby/3.3.0/gems/annotaterb-4.17.0/exe/annotaterb:18:in `<top (required)>'
        from bin/annotaterb:27:in `load'
        from bin/annotaterb:27:in `<main>'
```

This patch just make sure `ModelFilesGetter` always return an array.